# .github/FUNDING.yml: Lists funding platforms where {{AUTHOR_NAME}} accepts contributions.

github: { { GITHUB_USERNAME } }
buy_me_a_coffee: { { BUY_ME_A_COFFEE_USERNAME } }
ko_fi: { { KO_FI_USERNAME } }
liberapay: { { LIBERAPAY_USERNAME } }
open_collective: { { OPEN_COLLECTIVE_USERNAME } }
patreon: { { PATREON_USERNAME } }
